version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ims
      POSTGRES_PASSWORD: ims
      POSTGRES_DB: ims
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nodeapp:
    build:
      context: .
    ports:
      - "8082:3000"
    volumes:
      - /Users/harresh/Desktop/ims/server:/usr/src/app
    depends_on:
      - postgres
