"""
IMS Analytics Report Service
Generates downloadable PDF and CSV reports.
"""
import io
import csv
import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime


def _header_style():
    styles = getSampleStyleSheet()
    return ParagraphStyle(
        "IMSHeader", parent=styles["Title"],
        fontSize=22, textColor=colors.HexColor("#4F46E5"),
        spaceAfter=20, alignment=TA_CENTER,
    )

def _subtitle_style():
    styles = getSampleStyleSheet()
    return ParagraphStyle(
        "IMSSubtitle", parent=styles["Heading2"],
        fontSize=14, textColor=colors.HexColor("#334155"),
        spaceBefore=16, spaceAfter=8,
    )

def _body_style():
    styles = getSampleStyleSheet()
    return ParagraphStyle(
        "IMSBody", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#475569"),
    )


def generate_pdf(role, data, stats=None):
    """
    Generate a styled PDF report for the given role.
    Returns bytes of the PDF.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=0.5 * inch, bottomMargin=0.5 * inch)
    elements = []

    # Title
    elements.append(Paragraph("IMS Analytics Report", _header_style()))
    elements.append(Paragraph(
        f"Role: {role.upper()} &nbsp;|&nbsp; Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        _body_style()
    ))
    elements.append(Spacer(1, 20))

    # System stats
    if stats:
        elements.append(Paragraph("System Overview", _subtitle_style()))
        stat_data = [
            ["Metric", "Value"],
        ]
        for k, v in stats.items():
            label = k.replace("_", " ").title()
            val = f"${v:,.0f}" if "revenue" in k or "expense" in k else f"{v:,}"
            stat_data.append([label, val])

        tbl = Table(stat_data, colWidths=[3 * inch, 2 * inch])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
            ("TOPPADDING", (0, 0), (-1, 0), 10),
            ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F8FAFC")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F1F5F9")]),
        ]))
        elements.append(tbl)
        elements.append(Spacer(1, 20))

    # Data sections
    for section in data:
        elements.append(Paragraph(section.get("title", "Data"), _subtitle_style()))

        if section.get("type") == "table" and section.get("rows"):
            headers = section.get("headers", [])
            rows = section["rows"]
            table_data = [headers] + rows

            tbl = Table(table_data, repeatRows=1)
            tbl.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#6366F1")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F1F5F9")]),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]))
            elements.append(tbl)

        elif section.get("type") == "summary":
            for k, v in section.get("items", {}).items():
                elements.append(Paragraph(f"<b>{k}:</b> {v}", _body_style()))

        elements.append(Spacer(1, 16))

    # Footer
    elements.append(Spacer(1, 30))
    elements.append(Paragraph(
        "This report was auto-generated by IMS Analytics Engine. Data is accurate as of the generation timestamp.",
        ParagraphStyle("Footer", fontSize=8, textColor=colors.HexColor("#94A3B8"), alignment=TA_CENTER)
    ))

    doc.build(elements)
    return buf.getvalue()


def generate_csv(data_dict):
    """
    Generate a CSV from a dict of {section_name: DataFrame or list of dicts}.
    Returns bytes of the CSV.
    """
    buf = io.StringIO()
    writer = csv.writer(buf)

    for section_name, section_data in data_dict.items():
        writer.writerow([f"--- {section_name} ---"])
        if isinstance(section_data, pd.DataFrame):
            writer.writerow(section_data.columns.tolist())
            for _, row in section_data.iterrows():
                writer.writerow(row.tolist())
        elif isinstance(section_data, list):
            if section_data and isinstance(section_data[0], dict):
                writer.writerow(section_data[0].keys())
                for item in section_data:
                    writer.writerow(item.values())
        writer.writerow([])

    return buf.getvalue().encode("utf-8")
